---
title: "Reference Parking Lot"
html:
    toc: true
---

This is a searchable dump of references I've found useful. I will try to add reference descriptions/tags when I can, but please don't expect much organization here. 

The references are grouped into broad categories under headings. 

# Spatial Omics

**Spatial Data** <https://spatialdata.scverse.org/en/stable/> Mainly an object type to be used with different spatial omics data. It is still under development so the API may be subject to change. Uses anndata object to hold expression/fluorescence values so can be used with most scanpy-type analysis packages (scVI <https://scvi-tools.org>, scanpy <https://scanpy.readthedocs.io/en/stable/>, squidpy <https://squidpy.readthedocs.io/en/stable/)>

**SpaTopic** <https://xiyupeng.github.io/SpaTopic/> An R package for spatial topic modeling developed by Xiyu Peng. SpaTopic only requires cell type label and cell location, and can work across multiple samples. Works well with MIF data but could probably be used with other methods as well as long as cell type and location are known. 

<details>
<summary> Click for Citation </summary>
Peng, X., Smithy, J.W., Yosofvand, M. et al. Scalable topic modelling decodes spatial tissue architecture for large-scale multiplexed imaging analysis. Nat Commun 16, 6619 (2025). https://doi.org/10.1038/s41467-025-61821-y
</details>

## Segmentation

[cellpose](https://www.cellpose.org). Supposedly better than stardist in some cases. Still investigating this. 


# Jupyter
Jupyter widgets w/ plotly <https://quarto.org/docs/interactive/widgets/jupyter.html>